#index:
#    path: /
#    controller: App\Controller\ImageController::index

#upload:
#    path: /upload
#    controller: App\Controller\ImageController::upload

#download:
#    path: /download
#    controller: App\Controller\ImageController::download

delete:
    path: /images/{id}
    controller: App\Controller\ImageController::delete 

images:
    type:   rest
    resource: App\Controller\ImageController
    